language: python
sudo: false

cache:
  directories:
    - env

env:
  - LUA="lua 5.1"
  - LUA="lua 5.3"
  - LUA="luajit 2.1"

before_install:
  - pip install hererocks
  - hererocks env --$LUA -rlatest
  - source env/bin/activate

install:
  - luarocks install luacheck

script:
  - 'luacheck *.lua'
